language: node_js
node_js:
  - 0.10
env:
  global:
    - secure: "Ish9Fp5LErSmUFw+wwRifHrgJM44daz7OA1M43DdUAGEVI3R4MXFfDSfGMRhpUPh6PEO3ML/PHbhJghlcco3cSVStV2N0HfzLEnAbMbt/6bdTPw5s8i9u4K42KQRg25yt599lX+6xuNLg3eD1EVBHl+WhEjLZ0A099Roc2rqRdc="
    - secure: "Ab3PTxtKqYFdrYyUIOX1tyxwIm4bcJzEVXW7O8C9r5CCaS78exM/I9tzPcqnKminTWg5RpjIyIEGKkKCJOYx7dnGO1MhUEmCz1P3U3sOyfO/zD1yxIQD09KDVjccXfln/WlCIqE2Q64fxj54otQUF4MIG09C2aIIRhJEyBMgY+M="
cache:
  directories:
    - node_modules
before_install:
  - wget http://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.17/GraphicsMagick-1.3.17.tar.xz/download --output-document GraphicsMagick-1.3.17.tar.xz
  - tar xvf GraphicsMagick-1.3.17.tar.xz
  - cd GraphicsMagick-1.3.17
  - ./configure
  - make
  - sudo make install
  - cd ..
  - npm install -g gulp
script:
  - gulp deploy
