language: node_js
node_js:
  - 0.10
env:
  global:
    - secure: "Ish9Fp5LErSmUFw+wwRifHrgJM44daz7OA1M43DdUAGEVI3R4MXFfDSfGMRhpUPh6PEO3ML/PHbhJghlcco3cSVStV2N0HfzLEnAbMbt/6bdTPw5s8i9u4K42KQRg25yt599lX+6xuNLg3eD1EVBHl+WhEjLZ0A099Roc2rqRdc="
    - secure: "MzIsPEmLszhuMKi0wxI2OjhGvfX/ZYKy/Eq6lOQvodqKcpC2Z0DNvaQiHodjnMJ19t6JrFqrUcPA+fvPc6AlGe5V2+S7clUi98c6bnZJQAlUPjEc3k5k4e2oXPmZvPXAGSV4jApabrLBjGHc2F8/1S/IYaK5XM2pmRGiblZURL8="
cache:
  directories:
    - node_modules
before_install:
  - wget http://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.17/GraphicsMagick-1.3.17.tar.xz/download --output-document GraphicsMagick-1.3.17.tar.xz
  - tar xvf GraphicsMagick-1.3.17.tar.xz
  - cd GraphicsMagick-1.3.17
  - ./configure
  - make
  - sudo make install
  - cd ..
  - npm install -g gulp
script:
  - gulp deploy
