language: node_js
node_js:
  - 0.10
env:
  global:
    - secure: "Ish9Fp5LErSmUFw+wwRifHrgJM44daz7OA1M43DdUAGEVI3R4MXFfDSfGMRhpUPh6PEO3ML/PHbhJghlcco3cSVStV2N0HfzLEnAbMbt/6bdTPw5s8i9u4K42KQRg25yt599lX+6xuNLg3eD1EVBHl+WhEjLZ0A099Roc2rqRdc="
    - secure: "MzIsPEmLszhuMKi0wxI2OjhGvfX/ZYKy/Eq6lOQvodqKcpC2Z0DNvaQiHodjnMJ19t6JrFqrUcPA+fvPc6AlGe5V2+S7clUi98c6bnZJQAlUPjEc3k5k4e2oXPmZvPXAGSV4jApabrLBjGHc2F8/1S/IYaK5XM2pmRGiblZURL8="
cache:
  directories:
    - node_modules
before_install:
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install imagick-beta
  - npm install -g gulp
script:
  - gulp deploy
